{% set name = "chiscore" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b001cd751f5db1c0bbd0b0d775072f1a66a4a9015c34ca2f8b1edc2cc3b0312

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >3
    - setuptools >=49.6.0
  run:
    - chi2comb-py >=0.0.4
    - numpy >=1.17
    - pytest >=5
    - pytest-doctestplus >=0.8.0
    - python >3
    - scipy >=1.0.1

test:
  imports:
    - chiscore
  commands:
    - python -c "import sys; import chiscore; sys.exit(chiscore.test())"

about:
  home: https://github.com/limix/chiscore
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Test statistics derived from linear combination of chi-squared distributions
  dev_url: https://github.com/limix/chiscore

extra:
  recipe-maintainers:
    - Horta
