{% set name = "chiscore" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c7e184466b64f5a6dae6353d87a3573d7d525be695e246483bbc28037541e2c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pytest-runner
    - python >3
    - setuptools >=39.0.1
    - pip
  run:
    - python >3
    - chi2comb-py >=0.0.4
    - pytest-doctestplus >=0.3.0
    - scipy >=1.0.1
    - numpy >=1.14.3

test:
  imports:
    - chiscore
  commands:
    - python -c "import sys; import chiscore; sys.exit(chiscore.test())"

about:
  home: https://github.com/limix/chiscore
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Test statistics derived from linear combination of chi-squared distributions
  dev_url: https://github.com/limix/chiscore

extra:
  recipe-maintainers:
    - Horta
