travis:
  secure:
    BINSTAR_TOKEN: hS4LGFgH3wxdwRAnSYRmBtmrLkoIwNEHmyLZr9VaXPoFZI7ntOh46dvYFoBUYbrHBTTkVZJ0AsKNLKRYjoWVck7x0x63oPiSx1krzAyVWIIPh0j7Xf9lAAFlqdu2EsKoGv7UkXrqo5+0KKcdVuYE4KVX94d4kvOBGjluXYRkqaOh27Gh2rc9JEiNbZZrSjIWHmj0n676OG0RttT58GUUL9dzBS6h/H5k143iOsbdoDBrinwkZ5dEDKLVuRE7B5u3EvV2THNyGU4Th23ZyhYM6rtZ/eeLXZvyS1nmMQZnV/OO1gssDfyadoypE7nca8R5ZzlCCxIBTnPtJoHw1GyASIArJProSsGwrpdEBiDQBpV/HyLcZYJSdZuq/A/QNih2DgRB2sz3hbLjkNKzpI5OpREfmuSxekvmII2L6F8e7gZjdXqTaq9guB1MalilWZKfEvz7OI2wwaet5PRXbTl/m6EWqjh3fUaS/IxhONnXvr065LuTikFfTRWo9FpJlu4a3yYvQxmE17imU70NQyhf1sDRzTncbM+CYomoM6KciBqC3jdLZxDnc02vECWcddFx2zZEK7lg9k8a9Zac7heumbOwO8iTgznAF83uGWiIqr0qEL3o9QOWT4/Wz+yD2RpGeV7CWvFdjs1yvfd6tHoGB/kTx0b/mKGCm2kr5ruqSGs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
